---
- name: Checking Mariadb containers
  import_role:
    role: service-check

- name: Wait for MariaDB service to be ready through VIP
  kolla_toolbox:
    container_engine: "{{ kolla_container_engine }}"
    module_name: mysql_query
    module_args:
      ca_cert: "{{ openstack_cacert if database_enable_tls_internal | bool else omit }}"
      login_user: "{{ mariadb_shard_database_user }}"
      login_password: "{{ database_password }}"
      login_host: "{{ database_address }}"
      query: "SHOW DATABASES;"
  register: result
  until: result is success
  changed_when: False
  retries: 6
  delay: 10
  become: true
